#!/usr/bin/env python3
"""
WWB (Who What Benchmark) accuracy comparison for Gemma4:
  HF original (FP32/BF16) vs OpenVINO INT4.

Methodology
-----------
  GT (Ground Truth) : Reference answers generated by the original
                      unquantized HuggingFace model on CPU.  These are
                      the "correct" baseline we trust.
  Target            : Answers generated by the INT4-quantized OpenVINO
                      model (via openvino.genai VLMPipeline) on GPU.
  Score             : Cosine similarity of sentence embeddings between
                      GT and Target (using sentence-transformers/all-mpnet-base-v2,
                      the default scorer in the official openvino.genai WWB tool).
                      Also computes FDT/SDT token-divergence metrics.

                      Similarity >= 0.97 → Excellent quantization quality
                      Similarity >= 0.95 → Good
                      Similarity >= 0.90 → Acceptable
                      Similarity <  0.90 → Poor (may need re-quantization)

Usage
-----
  # Step 1 – Ground Truth (slow, runs on CPU with the original HF model)
  python run_wwb_gemma4.py --step gt --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov

  # Step 2 – Target (fast, runs on GPU with the INT4 OpenVINO model)
  python run_wwb_gemma4.py --step target --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov

  # Step 3 – Score only (compute metrics from saved CSVs)
  python run_wwb_gemma4.py --step score --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov

  # All steps sequentially
  python run_wwb_gemma4.py --step all --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov

Prerequisites
-------------
  pip install transformers torch sentence-transformers openvino-genai

  The HF model (google/gemma-4-E4B-it) can be downloaded with:
    huggingface-cli download google/gemma-4-E4B-it --local-dir ./gemma-4-E4B-it-hf
"""

import argparse
import csv
import os
import sys
import time
from pathlib import Path

# ── Defaults ────────────────────────────────────────────────────────────────────
DEFAULT_GT_CSV        = "wwb_gemma4_gt.csv"
DEFAULT_TARGET_CSV    = "wwb_gemma4_target.csv"
DEFAULT_MAX_NEW_TOKENS = 512
DEFAULT_NUM_SAMPLES    = 16   # use all 16 prompts for better coverage
DEFAULT_DEVICE         = "GPU"

# 16 diverse text-only prompts (covers science, coding, literature, economics,
# biology, technology).  For more rigorous evaluation, consider using a standard
# dataset such as squad, lambada, or wikitext with the official WWB CLI tool.
TEXT_PROMPTS = [
    "Explain quantum computing in simple terms.",
    "What are the main differences between Python and JavaScript?",
    "Write a short poem about the ocean.",
    "Describe the process of photosynthesis.",
    "What are the benefits of regular exercise?",
    "Explain how a neural network works.",
    "What is the theory of relativity?",
    "Describe the water cycle in nature.",
    "What are the key features of object-oriented programming?",
    "Explain the concept of supply and demand in economics.",
    "What causes earthquakes?",
    "Describe the lifecycle of a butterfly.",
    "What is blockchain technology?",
    "Explain how vaccines work.",
    "What are renewable energy sources and why are they important?",
    "Describe the structure of DNA.",
]


def generate_gt(hf_model_dir: str, gt_csv: str, num_samples: int, max_new_tokens: int):
    """Generate ground truth answers from HF original model on CPU."""
    import torch
    from transformers import AutoModelForImageTextToText, AutoProcessor

    prompts = TEXT_PROMPTS[:num_samples]
    print(f"\n{'='*60}")
    print(f"  Step 1: Ground Truth Generation (HF, CPU)")
    print(f"  Model:  {hf_model_dir}")
    print(f"  Prompts: {len(prompts)}, max_new_tokens: {max_new_tokens}")
    print(f"{'='*60}\n")

    print("Loading HF model (this may take a few minutes)...")
    t0 = time.perf_counter()
    processor = AutoProcessor.from_pretrained(hf_model_dir)
    model = AutoModelForImageTextToText.from_pretrained(
        hf_model_dir,
        torch_dtype=torch.float32,
        device_map="cpu",
    )
    model.eval()
    load_time = time.perf_counter() - t0
    print(f"Model loaded in {load_time:.1f}s")

    answers = []
    for i, prompt in enumerate(prompts):
        print(f"\n[{i+1}/{len(prompts)}] Prompt: {prompt[:60]}...")
        t1 = time.perf_counter()

        # Use chat template for proper formatting
        messages = [{"role": "user", "content": [{"type": "text", "text": prompt}]}]
        input_text = processor.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
        inputs = processor(text=input_text, return_tensors="pt")

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=False,
            )

        # Crop the input tokens
        generated_ids = outputs[:, inputs["input_ids"].shape[-1]:]
        answer = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
        elapsed = time.perf_counter() - t1
        num_tokens = generated_ids.shape[-1]
        print(f"  Generated {num_tokens} tokens in {elapsed:.1f}s ({num_tokens/elapsed:.1f} tok/s)")
        print(f"  Answer: {answer[:120]}...")
        answers.append(answer)

    # Save to CSV
    with open(gt_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["prompts", "answers"])
        for p, a in zip(prompts, answers):
            writer.writerow([p, a])
    print(f"\nGround truth saved to {gt_csv}")
    return prompts, answers


def generate_target(ov_model_dir: str, gt_csv: str, target_csv: str,
                    num_samples: int, max_new_tokens: int, device: str):
    """Generate answers from OpenVINO GenAI VLMPipeline (INT4)."""
    import openvino_genai as ov_genai

    # Load prompts from GT CSV
    if not os.path.exists(gt_csv):
        print(f"Error: {gt_csv} not found. Run --step gt first.")
        sys.exit(1)

    prompts = []
    with open(gt_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            prompts.append(row["prompts"])

    prompts = prompts[:num_samples]

    print(f"\n{'='*60}")
    print(f"  Step 2: Target Generation (GenAI VLMPipeline, {device})")
    print(f"  Model:  {ov_model_dir}")
    print(f"  Prompts: {len(prompts)}, max_new_tokens: {max_new_tokens}")
    print(f"{'='*60}\n")

    print("Loading VLMPipeline...")
    t0 = time.perf_counter()
    pipe = ov_genai.VLMPipeline(ov_model_dir, device)
    load_time = time.perf_counter() - t0
    print(f"Model loaded in {load_time:.1f}s")

    config = ov_genai.GenerationConfig()
    config.max_new_tokens = max_new_tokens

    answers = []
    for i, prompt in enumerate(prompts):
        print(f"\n[{i+1}/{len(prompts)}] Prompt: {prompt[:60]}...")
        t1 = time.perf_counter()

        result = pipe.generate(prompt, generation_config=config)
        answer = result.texts[0] if hasattr(result, 'texts') else str(result)
        elapsed = time.perf_counter() - t1
        metrics = result.perf_metrics
        tok_count = metrics.get_num_generated_tokens()
        throughput = metrics.get_throughput().mean
        print(f"  Generated {tok_count} tokens in {elapsed:.1f}s ({throughput:.1f} tok/s)")
        print(f"  Answer: {answer[:120]}...")
        answers.append(answer)

    # Save to CSV
    with open(target_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["prompts", "answers"])
        for p, a in zip(prompts, answers):
            writer.writerow([p, a])
    print(f"\nTarget answers saved to {target_csv}")
    return prompts, answers


def compute_score(hf_model_dir: str, gt_csv: str, target_csv: str):
    """Compute similarity metrics between GT and target answers."""
    from sentence_transformers import SentenceTransformer
    import numpy as np

    if not os.path.exists(gt_csv):
        print(f"Error: {gt_csv} not found. Run --step gt first.")
        sys.exit(1)
    if not os.path.exists(target_csv):
        print(f"Error: {target_csv} not found. Run --step target first.")
        sys.exit(1)

    # Load data
    gt_prompts, gt_answers = [], []
    with open(gt_csv, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            gt_prompts.append(row["prompts"])
            gt_answers.append(row["answers"])

    tgt_prompts, tgt_answers = [], []
    with open(target_csv, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            tgt_prompts.append(row["prompts"])
            tgt_answers.append(row["answers"])

    assert len(gt_answers) == len(tgt_answers), "Mismatch in number of answers"

    print(f"\n{'='*60}")
    print(f"  Step 3: Accuracy Scoring")
    print(f"  Similarity model: sentence-transformers/all-mpnet-base-v2")
    print(f"  Samples: {len(gt_answers)}")
    print(f"{'='*60}\n")

    # Load sentence transformer for similarity
    print("Loading similarity model...")
    sim_model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

    # Compute embeddings
    print("Computing embeddings...")
    gt_embeddings = sim_model.encode(gt_answers, convert_to_numpy=True)
    tgt_embeddings = sim_model.encode(tgt_answers, convert_to_numpy=True)

    # Cosine similarity per sample
    similarities = []
    for g, t in zip(gt_embeddings, tgt_embeddings):
        cos_sim = np.dot(g, t) / (np.linalg.norm(g) * np.linalg.norm(t))
        similarities.append(cos_sim)

    # Token divergence metrics (FDT, SDT)
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(hf_model_dir)

    fdt_list = []  # First Divergent Token position
    sdt_list = []  # Sum of Divergent Tokens
    fdt_norm_list = []
    sdt_norm_list = []

    for gt_ans, tgt_ans in zip(gt_answers, tgt_answers):
        gt_tokens = tokenizer.encode(gt_ans)
        tgt_tokens = tokenizer.encode(tgt_ans)
        max_len = max(len(gt_tokens), len(tgt_tokens))
        min_len = min(len(gt_tokens), len(tgt_tokens))

        # FDT: position of first divergent token
        fdt = min_len  # default if one is prefix of other
        for j in range(min_len):
            if gt_tokens[j] != tgt_tokens[j]:
                fdt = j
                break
        fdt_list.append(fdt)
        fdt_norm_list.append(fdt / max_len if max_len > 0 else 1.0)

        # SDT: count of divergent tokens
        sdt = 0
        for j in range(max_len):
            gt_t = gt_tokens[j] if j < len(gt_tokens) else -1
            tgt_t = tgt_tokens[j] if j < len(tgt_tokens) else -2
            if gt_t != tgt_t:
                sdt += 1
        sdt_list.append(sdt)
        sdt_norm_list.append(sdt / max_len if max_len > 0 else 0.0)

    # Print per-sample results
    print(f"\n{'─'*90}")
    print(f"  {'#':>3}  {'Similarity':>10}  {'FDT':>5}  {'FDT norm':>9}  {'SDT':>5}  {'SDT norm':>9}  Prompt")
    print(f"{'─'*90}")
    for i in range(len(gt_answers)):
        print(f"  {i+1:>3}  {similarities[i]:>10.4f}  {fdt_list[i]:>5}  {fdt_norm_list[i]:>9.4f}  {sdt_list[i]:>5}  {sdt_norm_list[i]:>9.4f}  {gt_prompts[i][:40]}...")
    print(f"{'─'*90}")

    # Aggregate metrics
    avg_sim = np.mean(similarities)
    avg_fdt = np.mean(fdt_list)
    avg_fdt_norm = np.mean(fdt_norm_list)
    avg_sdt = np.mean(sdt_list)
    avg_sdt_norm = np.mean(sdt_norm_list)

    print(f"\n{'='*60}")
    print(f"  AGGREGATE METRICS")
    print(f"{'='*60}")
    print(f"  Similarity (↑ better, best=1.0) : {avg_sim:.4f}")
    print(f"  FDT        (↑ better)           : {avg_fdt:.1f}")
    print(f"  FDT norm   (↑ better, best=1.0) : {avg_fdt_norm:.4f}")
    print(f"  SDT        (↓ better, best=0)   : {avg_sdt:.1f}")
    print(f"  SDT norm   (↓ better, best=0.0) : {avg_sdt_norm:.4f}")
    print(f"{'='*60}")

    if avg_sim >= 0.97:
        print(f"\n  ✔ Excellent INT4 quantization quality (similarity >= 0.97)")
    elif avg_sim >= 0.95:
        print(f"\n  ✔ Good INT4 quantization quality (similarity >= 0.95)")
    elif avg_sim >= 0.90:
        print(f"\n  ⚠ Acceptable INT4 quantization quality (similarity >= 0.90)")
    else:
        print(f"\n  ✗ Poor INT4 quantization quality (similarity < 0.90)")

    # Show worst examples
    print(f"\n{'─'*60}")
    print(f"  Worst 3 examples by similarity:")
    print(f"{'─'*60}")
    worst_idx = np.argsort(similarities)[:3]
    for rank, idx in enumerate(worst_idx):
        print(f"\n  #{rank+1} (sim={similarities[idx]:.4f}):")
        print(f"    Prompt:    {gt_prompts[idx]}")
        print(f"    GT:        {gt_answers[idx][:150]}...")
        print(f"    INT4:      {tgt_answers[idx][:150]}...")

    return avg_sim


def main():
    parser = argparse.ArgumentParser(
        description="WWB accuracy comparison: Gemma4 HF original vs OpenVINO INT4",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Example workflow:
  python run_wwb_gemma4.py --step gt     --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov
  python run_wwb_gemma4.py --step target --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov
  python run_wwb_gemma4.py --step score  --hf-model ./gemma-4-E4B-it-hf --ov-model ./gemma-4-E4B-it-ov
""")
    parser.add_argument("--step", choices=["gt", "target", "score", "all"], required=True,
                        help="Which step to run: gt, target, score, or all")
    parser.add_argument("--hf-model", required=True,
                        help="Path to the original HuggingFace model directory (e.g., ./gemma-4-E4B-it-hf)")
    parser.add_argument("--ov-model", required=True,
                        help="Path to the OpenVINO INT4 model directory (e.g., ./gemma-4-E4B-it-ov)")
    parser.add_argument("--gt-csv", default=DEFAULT_GT_CSV,
                        help=f"Output CSV for ground truth (default: {DEFAULT_GT_CSV})")
    parser.add_argument("--target-csv", default=DEFAULT_TARGET_CSV,
                        help=f"Output CSV for target answers (default: {DEFAULT_TARGET_CSV})")
    parser.add_argument("--num-samples", type=int, default=DEFAULT_NUM_SAMPLES,
                        help=f"Number of prompts to evaluate (default: {DEFAULT_NUM_SAMPLES})")
    parser.add_argument("--max-new-tokens", type=int, default=DEFAULT_MAX_NEW_TOKENS,
                        help=f"Max tokens per answer (default: {DEFAULT_MAX_NEW_TOKENS})")
    parser.add_argument("--device", default=DEFAULT_DEVICE, choices=["CPU", "GPU"],
                        help=f"Device for OV model inference (default: {DEFAULT_DEVICE})")
    args = parser.parse_args()

    if args.step in ("gt", "all"):
        generate_gt(args.hf_model, args.gt_csv, args.num_samples, args.max_new_tokens)
    if args.step in ("target", "all"):
        generate_target(args.ov_model, args.gt_csv, args.target_csv,
                        args.num_samples, args.max_new_tokens, args.device)
    if args.step in ("score", "all"):
        compute_score(args.hf_model, args.gt_csv, args.target_csv)


if __name__ == "__main__":
    main()
